name:                haskup
version:             0.1.0.0
github:              "snoyberg/haskwrap"
license:             BSD3
author:              "Michael Snoyman"
maintainer:          "michael@snoyman.com"
copyright:           "2021 Michael Snoyman"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Wrapper executables that install a Haskell toolchain
category:            Development
description:         Please see the README on GitHub at <https://github.com/snoyberg/haskwrap#readme>

dependencies:
- base >= 4.14 && < 5
- rio

library:
  source-dirs: src
  dependencies:
  - stack >= 2.7 && < 2.8
  - rio-prettyprint
  - pantry

executables:
  haskup:
    main:                haskup-main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - optparse-simple
    - haskup
    - transformers

  haskwrap:
    main:                haskwrap.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    - -rtsopts=ignoreAll
    dependencies:
    - haskup

  installer-generator:
    main:                installer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - nsis
