name: Release

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '**'
  workflow_dispatch:

jobs:
  sanity:
    name: Linux/Mac
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      - shell: bash
        name: Build and run tests
        run: |
          set -ex
          stack upgrade
          stack --version
          stack test --no-terminal --copy-bins --local-bin-path bin
      - name: Upload bindist
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: bin/*
  integration-tests:
    name: Windows
    runs-on: windows-latest
    env:
      STACK_ROOT: "c:\sr"
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: c:/sr
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      - name: Install NSIS
        run: choco install nsis-unicode -y
      - shell: bash
        name: Build and run tests
        run: |
          set -ex
          stack upgrade
          stack --version
          stack test --no-terminal --copy-bins --local-bin-path bin
      - name: Generate installer
        shell: cmd
        run: |
          bin\installer-generator.exe
          "c:\Program Files (x86)\NSIS\Unicode\makensis.exe" -V3 bin\haskup-installer.nsi
      - name: Upload bindist
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: bin/*
